**TO - DO - Task**

In [ ]:
# Task 1

def convert_units(conversion_type, value):
    """
    Converts a value between different units of measurement.

    Parameters:
    conversion_type (int): The type of conversion selected by the user.
        1 - Meters to Feet
        2 - Feet to Meters
        3 - Kilograms to Pounds
        4 - Pounds to Kilograms
        5 - Liters to Gallons
        6 - Gallons to Liters
    value (float): The numeric value to be converted.

    Returns:
    float: The converted value.
    """

    if conversion_type == 1:
        return value * 3.28084  # meters to feet
    elif conversion_type == 2:
        return value / 3.28084  # feet to meters
    elif conversion_type == 3:
        return value * 2.20462  # kg to pounds
    elif conversion_type == 4:
        return value / 2.20462  # pounds to kg
    elif conversion_type == 5:
        return value * 0.264172  # liters to gallons
    elif conversion_type == 6:
        return value / 0.264172  # gallons to liters
    else:
        return None


def main():
    print("==== Unit Converter ====")
    print("Select Conversion Type:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        choice = int(input("Enter your choice (1-6): "))

        if choice < 1 or choice > 6:
            print("Error: Invalid conversion type selected.")
            return

        value = float(input("Enter the value to convert: "))

        result = convert_units(choice, value)

        if result is not None:
            print(f"Converted value: {result:.4f}")
        else:
            print("Error: Conversion could not be performed.")

    except ValueError:
        print("Error: Please enter a valid numeric value.")


if __name__ == "__main__":
    main()

==== Unit Converter ====
Select Conversion Type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter your choice (1-6): 1
Enter the value to convert: 400
Converted value: 1312.3360


In [ ]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The maximum number in the list.
    """
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The minimum number in the list.
    """
    return min(numbers)


def main():
    print("==== Mathematical Operations on a List ====")
    print("Select Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter your choice (1-4): "))

        if choice < 1 or choice > 4:
            print("Error: Invalid operation selected.")
            return

        user_input = input("Enter numbers separated by spaces: ")

        # Convert input string to list of floats
        numbers = list(map(float, user_input.split()))

        if len(numbers) == 0:
            print("Error: The list cannot be empty.")
            return

        if choice == 1:
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif choice == 2:
            result = calculate_average(numbers)
            print(f"Average: {result}")
        elif choice == 3:
            result = find_maximum(numbers)
            print(f"Maximum: {result}")
        elif choice == 4:
            result = find_minimum(numbers)
            print(f"Minimum: {result}")

    except ValueError:
        print("Error: Please enter valid numeric values.")


if __name__ == "__main__":
    main()

==== Mathematical Operations on a List ====
Select Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 1
Enter numbers separated by spaces: 2 5 6 8
Sum: 21.0


**Exercise on List Manipulation**

In [ ]:
# 1. Extract Every Other Element:

def extract_every_other(lst):
    return lst[::2]


# Example usage
numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print(result)


[1, 3, 5]


In [ ]:
# 2. Slice a Sublist:

def get_sublist(lst, start, end):
    return lst[start:end+1]


# Example usage
numbers = [10, 20, 30, 40, 50, 60]
result = get_sublist(numbers, 1, 4)
print(result)

[20, 30, 40, 50]


In [ ]:
# 3. Reverse a List Using Slicing:
def get_sublist(lst):
    return lst[::-1]


# Example usage
numbers = [10, 20, 30, 40, 50, 60]
result = get_sublist(numbers)
print(result)

[60, 50, 40, 30, 20, 10]


In [ ]:
# 4. Remove the First and Last Elements:
def remove_first_last(lst):
    return lst[1:-1]


# Example usage
numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)
print(result)

[2, 3, 4]


In [ ]:
# 5. Get the First n Elements:
def get_first_n(lst, n):
    return lst[:n]


# Example usage
numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)
print(result)

[1, 2, 3]


In [ ]:
# 7. Extract Elements in Reverse Order:
def get_last_n(lst, n):
    return lst[-n:]


# Example usage
numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)
print(result)

[4, 5]


**Exercise on Nested List:**

In [ ]:
# 1. Flatten a Nested List:

def flatten(lst):
    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list


# Example usage
numbers = [[1, 2], [3, 4], [5]]
result = flatten(numbers)
print(result)

[1, 2, 3, 4, 5]


In [ ]:
# 2. Accessing Nested List Elements:

def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

# Example usage:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(lst, indices)
print(result)

6


In [ ]:
# 3. Sum of All Elements in a Nested List:

def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum nested lists
        else:
            total += item
    return total

# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))  # Output: 21

21


In [ ]:
# 4. Remove Specific Element from a Nested List:

def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

# Example usage:
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(lst, elem))

[[1], [3], [4, 5]]


In [ ]:
# 5. Find the Maximum Element in a Nested List:

def find_max(lst):
    max_val = float('-inf')  # Start with the smallest possible value
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))  # Recursively find max in sublist
        else:
            max_val = max(max_val, item)  # Compare with current item
    return max_val

# Example usage:
nested_list = [[1, 2], [3, [4, 5]], 6]
print(find_max(nested_list))

6


In [ ]:
# 6. Count Occurrences of an Element in a Nested List:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count in sublist
        elif item == elem:
            count += 1
    return count

# Example usage:
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(count_occurrences(lst, elem))

3


In [ ]:
# 7. Flatten a List of Lists of Lists:

def deep_flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # Recursively flatten sublists
        else:
            flat_list.append(item)
    return flat_list

# Example usage:
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_list))


[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
# 8. Nested List Average:

def average_nested(lst):
    def helper(lst):
        total = 0
        count = 0
        for item in lst:
            if isinstance(item, list):
                sub_total, sub_count = helper(item)
                total += sub_total
                count += sub_count
            else:
                total += item
                count += 1
        return total, count

    total_sum, total_count = helper(lst)
    return total_sum / total_count if total_count != 0 else 0

# Example usage:
nested_list = [[1, 2], [3, 4], [5, 6]]
print(average_nested(nested_list))

3.5


# **To - Do - NumPy**

In [2]:
import numpy as np

In [ ]:
# Problem - 1: Array Creation:

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_array)

# 2. Initialize an all one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. Ones 4x2 array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
full_array = np.full((3, 3), 7, dtype=int)
print("\n3. Full array (3x3 filled with 7):\n", full_array)

# 4. Return a new array of zeros with same shape and type as a given array
zeros_like_array = np.zeros_like(full_array)
print("\n4. Zeros like full_array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(full_array)
print("\n5. Ones like full_array:\n", ones_like_array)

# 6. Convert existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted numpy array:\n", numpy_array)

1. Empty 2x2 array:
 [[4.03780994e-315 0.00000000e+000]
 [6.84589500e-310 6.84590882e-310]]

2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like full_array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones like full_array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

6. Converted numpy array:
 [1 2 3 4]


In [ ]:
# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1.\n", arr1)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(0, 9).reshape(3, 3)
print("\n2.\n", arr2)

# 3. Create a 3x3 identity matrix
arr3 = np.eye(3)
print("\n3.\n", arr3)

# 4. Create a random array of size 30 and find the mean
arr4 = np.random.random(30)
mean_value = arr4.mean()
print("\n4.\nArray:\n", arr4)
print("Mean:", mean_value)

# 5. Create a 10x10 array with random values and find min and max
arr5 = np.random.random((10, 10))
print("\n5.\nMin:", arr5.min())
print("Max:", arr5.max())

# 6. Create a zero array of size 10 and replace 5th element with 1
arr6 = np.zeros(10)
arr6[4] = 1   # Index 4 = 5th element
print("\n6.\n", arr6)

# 7. Reverse an array
arr7 = np.array([1, 2, 0, 0, 4, 0])
reversed_arr7 = arr7[::-1]
print("\n7.\n", reversed_arr7)

# 8. Create a 2D array with 1 on border and 0 inside
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n8.\n", arr8)

# 9. Create an 8x8 checkerboard pattern
arr9 = np.zeros((8, 8), dtype=int)
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9.\n", arr9)

1.
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2.
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3.
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4.
Array:
 [0.07760163 0.41315385 0.19504287 0.76528337 0.674465   0.84331983
 0.67559033 0.02641322 0.1298193  0.60935762 0.79326038 0.37907564
 0.85136462 0.09596493 0.09443073 0.16649293 0.98356192 0.47321039
 0.12540338 0.52154693 0.68191129 0.5228358  0.36122261 0.24179399
 0.25583795 0.71163316 0.12221151 0.30235437 0.26867798 0.56946353]
Mean: 0.4310767015382454

5.
Min: 0.010595064725597236
Max: 0.9769834937875866

6.
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7.
 [0 4 0 0 2 1]

8.
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9.
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Problem - 3: Array Operations:

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays (x and y)
add_xy = x + y
print("1. Addition:\n", add_xy)

# 2. Subtract the two arrays (x and y)
sub_xy = x - y
print("\n2. Subtraction:\n", sub_xy)

# 3. Multiply the array with any integer (e.g., 3)
mul_x = x * 3
print("\n3. Multiply x by 3:\n", mul_x)

# 4. Square of each element
square_x = x ** 2
print("\n4. Square of x:\n", square_x)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\n5. Dot Products:")
print("v · w =", dot_vw)
print("x · v =", dot_xv)
print("x · y =\n", dot_xy)

# 6. Concatenation
# Concatenate x and y along rows
concat_xy_row = np.concatenate((x, y), axis=0)
print("\n6. Concatenate x and y along rows:\n", concat_xy_row)

# Concatenate v and w along column
concat_vw_col = np.vstack((v, w)).T
print("\nConcatenate v and w along column:\n", concat_vw_col)

# 7. Concatenate x and v
# This will give an error because dimensions do not match
# np.concatenate((x, v))  # Uncommenting this line will raise an error


1. Addition:
 [[ 6  8]
 [10 13]]

2. Subtraction:
 [[-4 -4]
 [-4 -3]]

3. Multiply x by 3:
 [[ 3  6]
 [ 9 15]]

4. Square of x:
 [[ 1  4]
 [ 9 25]]

5. Dot Products:
v · w = 219
x · v = [29 77]
x · y =
 [[19 22]
 [50 58]]

6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along column:
 [[ 9 11]
 [10 12]]


In [5]:
# Problem - 4: Matrix Operations:

# Given Matrices
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

# 1. Prove A.A−1 = I

A_inv = np.linalg.inv(A)     # Inverse of A
I = np.matmul(A, A_inv)         # A * A⁻¹

print("A inverse:\n", A_inv)
print("\nA * A⁻¹:\n", I)


A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [7]:
# Prove AB ̸= BA

AB = np.matmul(A, B)
BA = np.matmul(B, A)

print("AB:\n", AB)
print("\nBA:\n", BA)

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]


In [8]:
# Prove (AB)T = BTAT

left_side = (np.matmul(A, B)).T
right_side = np.matmul(B.T, A.T)

print("(AB)^T:\n", left_side)
print("\nB^T A^T:\n", right_side)

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]


In [15]:
# Solve Linear Equations Using Matrix Form

# Represent in Matrix Form AX=B
A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3,  1, -1]])

B_sys = np.array([-1, -3, 9])

A_sys_inv = np.linalg.inv(A_sys)
X = np.matmul(A_sys_inv, B_sys)

print("Solution using inverse method:\n", X)
print(f"x = {X[0]}\ny = {X[1]}\nz = {X[2]}")

Solution using inverse method:
 [ 2.  1. -2.]
x = 2.0
y = 1.0
z = -2.0


In [21]:
# Solve Directly Using np.linalg.inv()

X2 = np.linalg.solve(A_sys, B_sys)
print("Solution using np.linalg.solve():\n", X2)
print(f"x = {X2[0]}\ny = {X2[1]:.1f}\nz = {X2[2]}")

Solution using np.linalg.solve():
 [ 2.  1. -2.]
x = 2.0
y = 1.0
z = -2.0


**Experiment: How Fast is Numpy?**

Element-wise Addition

In [22]:
import time
import random

# Element-wise Addition using python lists:

# Create two lists of size 1,000,000
list1 = [random.random() for _ in range(1_000_000)]
list2 = [random.random() for _ in range(1_000_000)]

# Measure time for element-wise addition
start_time = time.time()

result_list = [a + b for a, b in zip(list1, list2)]

end_time = time.time()

print("Time taken using Python Lists:", end_time - start_time, "seconds")

Time taken using Python Lists: 0.15394949913024902 seconds


In [23]:
# Element-wise Addition using numpy arrays:

# Create two NumPy arrays of size 1,000,000
array1 = np.random.random(1_000_000)
array2 = np.random.random(1_000_000)

# Measure time for element-wise addition
start_time = time.time()

result_array = array1 + array2

end_time = time.time()

print("Time taken using NumPy Arrays:", end_time - start_time, "seconds")

Time taken using NumPy Arrays: 0.005778789520263672 seconds


Element-wise Multiplication

In [25]:
# Element-wise Multiplication using python lists:

start = time.time()

result = [a * b for a, b in zip(list1, list2)]

end = time.time()

print("Element-wise Multiplication (List):", end - start, "seconds")

Element-wise Multiplication (List): 0.10135412216186523 seconds


In [26]:
# Element-wise Multiplication using numpy arrays:
start = time.time()

result = array1 * array2

end = time.time()

print("Element-wise Multiplication (NumPy):", end - start, "seconds")

Element-wise Multiplication (NumPy): 0.028599023818969727 seconds


Dot product

In [27]:
# Dot product using python lists

start = time.time()

dot_product = sum(a * b for a, b in zip(list1, list2))

end = time.time()

print("Dot Product (List):", end - start, "seconds")

Dot Product (List): 0.1424274444580078 seconds


In [28]:
# Dot product using numpy arrays
start = time.time()

dot_product_np = np.dot(array1, array2)

end = time.time()

print("Dot Product (NumPy):", end - start, "seconds")

Dot Product (NumPy): 0.008746147155761719 seconds


Matrix Multiplication

In [31]:
# Using Python lists
# Create 1000x1000 matrices
size = 1000
A = [[random.random() for _ in range(size)] for _ in range(size)]
B = [[random.random() for _ in range(size)] for _ in range(size)]

start = time.time()

# Matrix multiplication using nested loops
result = [[0]*size for _ in range(size)]

for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Matrix Multiplication (List):", end - start, "seconds")

Matrix Multiplication (List): 345.3607409000397 seconds


In [30]:
# Using numpy arrays

A_np = np.random.random((1000, 1000))
B_np = np.random.random((1000, 1000))

start = time.time()

result_np = np.dot(A_np, B_np)

end = time.time()

print("Matrix Multiplication (NumPy):", end - start, "seconds")

Matrix Multiplication (NumPy): 0.06128215789794922 seconds
